### ISSUE TITLE
I don't have any issue 

### ISSUE THREAD

**Issue by ramanujana1729** [Rajagopalr3/CustomEditText#3]
I am just trying out things on github and learning how to put issues in github

[This is a link](http://youtube.com) and **kishan is  #bold**

![misty_morning_sunrise_7_by_fantasystock](https://user-images.githubusercontent.com/28920158/39480126-e87609e0-4d84-11e8-9a42-c5d5b6ed52d8.jpg)

**Comment by Rajagopalr3** [comment]
ok. then I will mark this as closed

**Comment by ramanujana1729** [comment]
Yep
