### ISSUE TITLE
How to set libIZO_setBorderColor programatically?

### ISSUE THREAD

**Issue by itvignes09** [Rajagopalr3/CustomEditText#7]
We can able set colors using XML but I don't know how to set color programmatically. Seems no option for that

**Comment by Rajagopalr3** [comment]
thanks for your valuable feedback. Will update this feature in next release.

**Comment by Rajagopalr3** [comment]
Have done the changes according to your question. Please upgrade the library version to 1.0.6. Let me know if any issues?.
Kindly close this loop if no errors
